mysite/apps/blog/urls.py
#coding=utf-8
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
  path('', views.index, name='index'),
  path('blog/', views.index, name='index'),
  path('blog/search/', views.blog_search, name="blog_search"),
  path('blog/categorys/', views.category, name="category"),
  path('blog/<path:sort>/<int:pk>/', views.detail, name='detail'),
  path('blog/<path:sort>/', views.sort_index, name='sort_index'),
  
   
]
#print(urlpatterns)

mysite/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]

app_name = 'DjangoUeditor'

if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    from django.urls import path

    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller),
        
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from . import views
from . import settings
#import django_comments
import xadmin
import DjangoUeditor


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),

    re_path(r'media/(?P<path>.*)', serve, {'document_root':settings.MEDIA_ROOT}),
    path('test/', views.test),

    path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('comment/', include('comment.urls')),
    path('', include('blog.urls')),
    
    
]

mysite/apps/blog/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.conf import settings

from DjangoUeditor.models import UEditorField


class Category(models.Model):
  name = models.CharField('分类', max_length=128)

  def __str__(self):
    return self.name

  class Meta:
    verbose_name = "博客分类"
    verbose_name_plural = verbose_name
    
class Tag(models.Model):
  name = models.CharField('标签', max_length=128)  

  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name = "博客标签"
    verbose_name_plural = verbose_name

class Blog(models.Model):

  state_choices = (
    ('publish', '发布'),
    ('unpublish', '不发布')
  )

  title = models.CharField('文章标题', max_length=128)
  author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
  img = models.ImageField(upload_to='blog_img/', null=True, blank=True, verbose_name='博客配图', max_length=100)
  body = UEditorField('正文', height=100, width=900, imagePath='uploadimg/', filePath='upload/', toolbars='besttome')
  state = models.CharField('状态', max_length=10, choices=state_choices, default="publish" )
  visits = models.PositiveIntegerField('访问量', default=0)
  comments = models.PositiveIntegerField('评论数', default=0)
  category = models.ForeignKey(Category, verbose_name='博客分类',on_delete=models.CASCADE)
  abstract = models.CharField('摘要', max_length=200, blank=True, default="")
  create_time = models.DateTimeField('创建时间', auto_now_add=True)
  modify_time = models.DateTimeField('修改时间', auto_now=True)

  def __str__(self):
    return self.title
  
  class Meta:
    ordering = ['-create_time']
    verbose_name = '博客'
    verbose_name_plural = verbose_name
 
  @property
  def img_url(self):
    if self.img and hasattr(self.img, 'url'):
      return self.img.url

    

mysite/apps/blog/views.py
#-*- coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *

from functools import wraps


#统计功能，装饰器
def zhandiantongji(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        categorys = Category.objects.all()
        blogs = Blog.objects.filter(state='publish')
        rand_blogs = Blog.objects.filter(state='publish').order_by("?")[:10]
        # print(rand_blogs)
        category_to_blogs ={}
        kwargs['categorys'] = categorys  
        kwargs['blogs'] = blogs
        kwargs['rand_blogs'] = rand_blogs
        for category_ in categorys:
            category_to_blogs[category_.name] = category_.blog_set.filter(state='publish')
        category_to_blogs = sorted(category_to_blogs.items(), key=lambda x:x[1].count(), reverse=True)
        kwargs['category_to_blogs'] = category_to_blogs
        return func(*args, **kwargs)
    return wrapper


@zhandiantongji
def index(request, **kwargs):
    categorys = kwargs.get('categorys', None)
    blogs = kwargs.get('blogs', None)
    rand_blogs = kwargs.get('rand_blogs', None)
    # print(rand_blogs)
    category_to_blogs = kwargs.get('category_to_blogs', None)
    page = request.GET.get('page', 1)
    paginator = Paginator(blogs, 10)
    try:
        page_blogs = paginator.page(page)
    except EmptyPage:
        page_blogs = paginator.page(1)
    except PageNotInteger:
        page_blogs = paginator.page(paginator.num_pages)
    return render(request, 'blog/blog_index.html', locals())


def detail(request, sort, pk, **kwargs):
    blog = Blog.objects.get(id=pk)
    category = blog.category.name
    #tag = blog.tag.all()[0].name
    return render(request, 'blog/blog_detail.html', locals())


@zhandiantongji
def sort_index(request, sort, **kwargs):
    #右侧栏分类、随机推荐
    category_to_blogs = kwargs.get('category_to_blogs', None)
    rand_blogs = kwargs.get('rand_blogs', None)
    try:
        category = Category.objects.get(name=sort)
        blogs = category.blog_set.filter(state='publish')
    except:
        return render(request, 'blog/blog_502.html', locals())
    page = request.GET.get('page', 1)
    paginator = Paginator(blogs, 10)
    try:
        page_blogs = paginator.page(page)
    except EmptyPage:
        page_blogs = paginator.page(1)
    except PageNotAnInteger:
        page_blogs = paginator.page(paginator.num_pages)
    #print(locals())
    return render(request, 'blog/blog_index.html', locals())


#搜索
@zhandiantongji
def blog_search(request, **kwargs):
    category_to_blogs = kwargs.get('category_to_blogs', None)
    rand_blogs = kwargs.get('rand_blogs', None)
    if request.method == "GET":
        search_ = request.GET.get('kw', None)  
        #print(search_)
        page_blogs = Blog.objects.filter(title__icontains=search_)
        return render(request, 'blog/blog_search.html', locals())


#按分类归档
@zhandiantongji
def category(request, **kwargs):
    rand_blogs = kwargs.get('rand_blogs', None)
    category_to_blogs = kwargs.get('category_to_blogs', None) 
    return render(request, 'blog/blog_category.html', locals())

  

mysite/apps/blog/templates/blog/blog_502.html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>很抱歉，没有找到关于#{{sort}}#的页面</center>

</body>
</html>

mysite/apps/blog/templates/blog/blog_category.html
{% extends 'blog/blog_index.html' %}
{% load staticfiles %}

{% block css %}
{{block.super}}
  <link rel="stylesheet"type="text/css" href="{% static 'blog/css/blog_category.css'%}"/>
{% endblock %}


{% block content %}
  <div class="content">
    {% for category_name,blog_queryset in category_to_blogs %}
      {% if blog_queryset %}
      <div class="content_index">       
            <p class="content_index_category">
              <span><i class="fa fa-hand-o-down fa-fw"></i>{{ category_name }}</span>
              <span style="display:inline-block;float:right"><a href="/blog/{{category_name}}/">更多<i class="fa fa-angle-double-right fa-fw"></i></a></span>
            </p>
            <ul class="content_index_list">
              {% for blog in blog_queryset %}
                <li>
                  <span class="fa fa-angle-right" style="padding-right:8px;"></span><span><a href="/blog/{{blog.category.name}}/{{blog.pk}}/">{{blog.title}}</a></span>
                  <span style="display:inline-block;float:right">{{blog.create_time|date:"Y-m-d"}}</span>
                </li>
              {% endfor %}
            </ul>   
      </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

mysite/apps/blog/templates/blog/blog_detail.html
{% extends 'blog/blog_index.html' %}
{% load blog_extras %}
{% load staticfiles %}



{% block title %}{{ blog.title }}{% endblock %}

{%block css%}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog_detail.css'%}"/> 
{% endblock %}

 
{% block content %}
<div class="content">

    <div class="content_path"><i class="fa fa-home fa-fw"></i>当前位置：<a href="/">Home</a> \ <a href="{% url 'blog:sort_index' category%}">{{category}}</a> \ <a href="#">{{blog.title}}</a> \</div>
    
      <div class="content_detail"><br>
        <h2 class="content_detail_title">{{blog.title}}</h2><hr>
<!---
        <ul class="content_detail_addition"> 
          <li class="fa fa-user"> <a href="#">{{blog.author}}</a> </li>
          <li class="fa fa-calendar"> {{blog.create_time.date}} </li>
          <li class="fa fa-comment"> 评论数({{blog.comment}}) </li> 
          <li class="fa fa-eye"> {{blog.visits}}</li> 
        </ul>
--->
        <div class="content_detail_body">
          {{blog.body|safe}}
        </div>
    </div>

    {% include 'comment/comment.html' %}

</div>
{% endblock %}


{% block sidebar%}
  <div class="sidebar">
    <p>文章目录</p>
  </div>
{% endblock %}

mysite/apps/blog/templates/blog/blog_index.html
{% extends 'main_base.html' %}
{% load staticfiles %}

<!--CSS继承-->
  {%block css%}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog_index.css'%}"/> 

  {% endblock %}
  
 
<!--博客列表-->
{% block content %}
  <div class="content">
    {% block content_path %}{%endblock%}

    {% if page_blogs  %}
        {% for blog in page_blogs %}
        <div class="content_index">
            <p class="content_index_title"><a href="{% url 'blog:detail'  blog.category.name blog.id %}">{{ blog.title }}</a></p>
            {% autoescape off %}
            <p class="content_index_abstract">{{blog.abstract}}</p>
            {% endautoescape %}
            <ul class="content_index_addition"> 
            <li><i class="fa fa-user fa-fw"></i> <a href="#">{{blog.author}}</a> </li>
            <li><i class="fa fa-calendar fa-fw"></i> {{blog.create_time|date:"Y-m-d H:m"}} </li>
            <li><i class="fa fa-tag fa-fw"></i><a href="/{{blog.category.name}}/">{{blog.category.name}}</a> </li>
            <li><i class="fa fa-comments fa-fw"></i>({{blog.comment}}) </li> 
            <li><i class="fa fa-eye fa-fw"></i> {{blog.visits}}</li> 
            </ul>
            
        </div>
        {% endfor %}

        <!--页码-->
        {%block paginator%}
        {% include 'blog/paginator.html' %}
        {% endblock %}

    {% else %}
        <p class="content_index"style="padding:50px 30px;">#未找到相关内容</p>

    {% endif %}
  </div>
{% endblock %}  

  <!--侧边栏-->
{% block sidebar %}
  <div class="sidebar">
     <!--站点信息-->
      <div class="sidebar_one">
        <p class="sidebar_title"><i class=" fa fa-refresh fa-spin fa-fw"></i>最新动态</p><hr />
        <p>增加评论功能</p>
      </div>

    <!--友情链接-->
    <div class="sidebar_link">
      <p class="sidebar_title "><i class="fa fa-link fa-fw"></i>友情链接</p><hr />
      <ul class="sidebar_link_list">
          <li><a href="https://www.eastnotes.com/" target="_blank">向东的笔记</a></li>
          <li><a href="https://www.dusaiphoto.com/" target="_blank">杜赛的个人网站</a></li>
          <li><a href="https://www.zmrenwu.com/" target="_blank">追梦人物</a></li>
          <li><a href="https://www.503error.com/" target="_blank">张志明</a></li>
          <li><a href="https://cuiqingcai.com/" target="_blank">静觅</a></li>
          <li><a href="https://www.yuanrenxue.com/" target="_blank">学python</a></li>
          <li><a href="https://yshblog.com/" target="_blank">杨仕航</a></li>
      </ul>
    </div>
    <!--分类目录-->
      <div class="sidebar_sort">
        <p class="sidebar_title"><i class="fa fa-sort fa-fw"></i>分类目录</p>
        <hr />
        <ul class="sidebar_sort_list">
          {% for category_name, blog_queryset in category_to_blogs %}
          {% if blog_queryset %}
          <li><a href="/blog/{{category_name}}/" >{{category_name}}</a></li>
          {%endif%}
          {% endfor %}
        </ul>
      </div>
      <!--归档-->
      <div class="sidebar_random">
        <p class="sidebar_title"><i class="fa fa-list fa-fw"></i>随机推荐</p><hr />
        <ul class="sidebar_random_list">
          {% for blog in rand_blogs%}
          <li>
            <a href="/blog/{{blog.category}}/{{blog.id}}/">{{blog.title}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
  </div>
{%endblock%}  

{% block footer %}
  <div class="footer">
      推开窗博客<i class="fa fa-copyright fa-fw" ></i>版权所有
  </div>
{% endblock %}

mysite/apps/blog/templates/blog/blog_search.html
{% extends 'blog/blog_index.html' %}
{% load staticfiles %}


    {% block content_path %}
    <p class="content_path" style="background-color:white;margin-bottom:2px;padding:3px;">
      <i class="fa fa-bell fa-fw"></i>包含关键字 #<span style="color:red;">{{search_}}</span>#的搜索结果<i class="fa fa-angle-double-right fa-fw"></i>
    </p>
    {%endblock%}
    

mysite/apps/blog/templates/blog/paginator.html
    <div class="paginator" style="margin-top:20px;text-align:center;">
      <ul class="paginator_list" style="margin:auto;width:80%;">
      {%  for page_num in paginator.page_range %}
        {% if paginator.num_pages > 1 %}
        <li class="paginator_list_page" style="display:inline-block;background-color:yellowgreen;">
          <a style="text-decoration:none; font-size:20px;padding:0 8px;" href="/blog/?page={{page_num}}">{{page_num}}</a></li>
        {%endif%}
      {% endfor %}
      </ul>
    </div>